<?php

function title_case_menu() {
    $items = array();
    $items['title_case'] = array(
            'title' => 'Title Case Generator',
            'page callback' => 'drupal_get_form',
            'page arguments' => array('title_case_form'),
            'access callback' => TRUE,
            'type' => MENU_NORMAL_ITEM,
        );
    $items['title_case_success_page'] = array(
            'title' => 'Success',
            'page callback' => 'title_case_success',
            'access callback' => TRUE,
            'type' => MENU_CALLBACK,
        );
    return $items;
}

function title_case_form() {
    $form['text_title_case'] = array(
        '#title' => 'Text to Title Case',
        '#type' => 'textfield',
        '#description' => t("Enter some text"),
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'LFG!',
    );

    return $form;
}

function title_case_submit($form, &$form_state) {
    $input_title = $form_state['values']['text_title_case'];
    $designated_words = array('a', 'an', 'the', 'at', 'by', 'for', 'in', 'of', 'on', 'to', 'up', 'and', 'as', 'but', 'or', 'nor');
    $input_title = (strtolower($input_title));
    $input_word_array = explode(" ", $input_title);
    $output_titlecased = array();
    foreach ($input_word_array as $word) {
        if (in_array($word, $designated_words)) {
            array_push($output_titlecased, $word);
        } else {
            array_push($output_titlecased, ucfirst($word));
        }
    }
    $final_title = implode(" ", $output_titlecased);
    for ($i =0; $i <= strlen($final_title); $i++)
    {
        $char = substr($final_title, $i, 1);
        if ($char == '-') {
            $final_title[$i + 1] = ucfirst(substr($final_title, $i + 1, 1));
        }
        if ($char == "'" && $final_title[$i + 1] !== "s") {
            $final_title[$i + 1] = ucfirst(substr($final_title, $i + 1, 1));
        }
    }

    $_SESSION['final_title'] = $title_case_output;
    $form_state['redirect'] = 'title_case_success_page';
}

function title_case_success() {
    $result = $_SESSION['final_tilte'];
    return "title cased text: $result";
}
